<?php

namespace Entegrator\TrendyolApi\V1\Tests\Models\Product\Brand\Request\ByNameRequest;

use Entegrator\TrendyolApi\V1\Models\Product\Brand\Request\ByNameRequest\QueryParameter;
use PHPUnit\Framework\TestCase;
use function Webmozart\Assert\Tests\StaticAnalysis\string;

class QueryParameterTest extends TestCase
{

    private string $fString;

    function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->fString = uniqid();
    }


    function testGetName() {
        $qp = new QueryParameter($this->fString);

        $actual = $qp->getName();

        $this->assertSame($this->fString,$actual);
}

function test__ToString() {
        $qp = new QueryParameter($this->fString);

        $actual = (string) $qp;

        $this->assertSame("name=".$this->fString,$actual);
}

    function testToArray() {
        $qp = new QueryParameter($this->fString);

        $actual = $qp->toArray();

        $this->assertSame(['name' => $this->fString],$actual);
    }

}